### ISSUE TITLE
Fetch all available languages

### ISSUE THREAD

**Issue by philip-akerfeldt** [rburgst/wp-graphql-wpml#1]
Hi! 
First off, thanks for developing this plugin! 🚀 

I have a question about something that would be really nice to get from this plugin. It would be really good if the plugin created a node for all the available languages on a site. Does anyone know how to achieve this?

Something like this:
```
  # Get all configured languages
    languages {
        name
        code
    }
```

Thanks!

**Comment by rburgst** [comment]
thanks for the suggestion, I will try and squeeze this in as soon as I find the time

**Comment by philip-akerfeldt** [comment]
Great! Some information that I would find extremely attractive would be the following:
```
allWordpressLanguages {
      nodes {
        code
        translated_name
        native_name
      }
    }
```
