### ISSUE TITLE
No language data when query from external 

### ISSUE THREAD

**Issue by ngongoll** [rburgst/wp-graphql-wpml#12]
wp-graphlql is working fine for default language.

i installed wp-graphql-wpml but when i send my query. The data for for the second language is empty. It works fine with the GraphIQL.

My query
`query MyQuery {
  menus {
    nodes {
      name
      slug
      menuItems(where: {parentId: "null"}) {
        nodes {
          title
          label
        }
      }
    }
  }
}`
response external
`{
          "name": "Hauptmenü",
          "slug": "hauptmenue",
          "menuItems": {
            "nodes": []
          }
        }`

response GraphIQL
`{
          "name": "Hauptmenü",
          "slug": "hauptmenue",
          "menuItems": {
            "nodes": [
              {
                "title": null,
                "label": "Umsatzsteuer"
              }
             ]
           }
}`

do have any ideas? thanks for your reply

**Comment by rburgst** [comment]
please try the latest version, it is probably fixed now. The problem was that queries through graphql (outside of the GraphiQL wordpress UI) dont have authentication attached (even if you include BASIC auth), therefore, this info was considered "private" and I had to hack around it to make it appear via external queries.

**Comment by rburgst** [comment]
see 10a2a46b0e24c7f9859478e3abb7306268b1d462 and 6c43583e77efd03aa0319fb3e45ac18d52f9798f

**Comment by ngongoll** [comment]
Works fine. Thanks for the quick hack. i have to dive deeper in creating plugins for wpgraphql. Its looks promising for new projects with headless cms.

**Comment by ngongoll** [comment]
Hi i have still trouble getting all of the menu data. Can you help me debug this? Where is the query build or better ask where are the best points to set a logger.
THX for you help

**Comment by rburgst** [comment]
The usual fix is done via https://github.com/rburgst/wp-graphql-wpml/blob/master/wp-graphql-wpml.php#L510 where wp-graphql checks whether the menu item (or menu itself) is private.

**Comment by ngongoll** [comment]
I think it is more that the data is inkonsistent. i even don't get the correct information in the graphIDE. is there something like a   mysql query which i can debug?

**Comment by rburgst** [comment]
you can find a couple of relevant queries here: https://github.com/wp-graphql/wp-graphql/issues/1768
