### ISSUE TITLE
Have not found a way to fetch Posts or Post by `locale`

### ISSUE THREAD

**Issue by retzion** [rburgst/wp-graphql-wpml#13]
Thank you to anyone who can help with this. Maybe my approach is wrong and you can tell me how you are getting the results I'm looking for.

```
fragment AuthorFields on User {
  name
  firstName
  lastName
  avatar {
    url
  }
}

fragment PostFields on Post {
  title
  excerpt
  slug
  date
  featuredImage {
    node {
      sourceUrl
    }
  }
  author {
    node {
      ...AuthorFields
    }
  }
  categories {
    edges {
      node {
        name
      }
    }
  }
  tags {
    edges {
      node {
        name
      }
    }
  }
}

fragment AdditionalFields on Post {
  content
  locale {
    locale
  }
  translations {
    post_title
    locale
    href
  }
  seo {
    metaDesc
    metaKeywords
    metaRobotsNofollow
    metaRobotsNoindex
    opengraphAuthor
    opengraphDescription
    focuskw
    cornerstone
    canonical
    breadcrumbs {
      text
      url
    }
    opengraphImage {
      altText
      link
      uri
      title
      sourceUrl
    }
    opengraphModifiedTime
    opengraphPublishedTime
    opengraphPublisher
    opengraphSiteName
    opengraphTitle
    opengraphType
    opengraphUrl
    title
    twitterDescription
    twitterTitle
    twitterImage {
      altText
      caption
      uri
      sourceUrl
    }
  }
}

query PostBySlug($id: ID!, $idType: PostIdType!) {
  post(id: $id, idType: $idType) {
    ...PostFields
    ...AdditionalFields
  }
}

query AllPosts($length: Int!, $after: String) {
  posts(first: $length, after: $after, where: {orderby: {field: DATE, order: DESC}}) {
    edges {
      node {
        title
        excerpt
        slug
        date
        featuredImage {
          node {
            sourceUrl
          }
        }
        author {
          node {
            name
            firstName
            lastName
            avatar {
              url
            }
          }
        }
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}
```

**Comment by kblizeck** [comment]
@rburgst Pinging this too - currently querying `posts` returns all posts in all languages - I need a way to query just English, or just Spanish, to allow for pagination.

**Comment by rburgst** [comment]
I know this is an urgent request however, at the moment I am very busy with other things.

**Comment by bonellicious** [comment]
+ 1

**Comment by federicocappellotto97** [comment]
follow

**Comment by florianschommertz** [comment]
You can do this: https://DOMAIN.com/graphql?locale=en

**Comment by rburgst** [comment]
@macharest  this looks really good. Would you mind creating a PR so we can integrate this into this plugin?

**Comment by macharest** [comment]
@rburgst Sure I could probably integrate this as a PR in the next few days or so.

**Comment by revnelson** [comment]
@macharest This works well, thank you! In many front end clients (such as apollo or urql) this would require destroying the client instance and re-creating a new client on locale change. It seems like a more elegant solution may be to support reading a request header from the client. Something like "locale: en" for example. Then we can simply invalidate cache on locale change to get fresh queries. Is this something that's possible?

**Comment by rburgst** [comment]
@RevNelson I am not sure I understand, the PR https://github.com/rburgst/wp-graphql-wpml/pull/32 adds a new filter option where you can choose the language via your normal Query.

**Comment by eliawk** [comment]
@rburgst @macharest is it possible to implement the **where** also on singular item like **Page** and **Post**?
for example if I want to query a page by slug I need to filter also for language in case I have the same slug on two different languages, es `test` and `test?lang=en`

**Comment by andyjamesn** [comment]
> @rburgst @macharest is it possible to implement the **where** also on singular item like **Page** and **Post**? for example if I want to query a page by slug I need to filter also for language in case I have the same slug on two different languages, es `test` and `test?lang=en`

I am also looking for this solution to return a single translated post

eg: I need to retrieve a single post by its slug. In WPGraphQL there is no way to retrieve a single post by ID type slug when using Posts. This only works on singular Post

Since where and wpmlLanguage: "es" only works on pages I am unable to retrieve a single post in the specific language

Something like this would be ideal

`post(id: "some/post", idType: URI, wpmlLanguage: "es") {`

**Comment by alancwoo** [comment]
@rburgst also running into the same problem as @andyjamesn, being unable to just query a post by its slug and the desired language. I sort of see why, since slugs are meant to be unique, but in the context of wpml where slugs may be the same, it would be incredibly useful.

I'm unable to think of a solution that doesn't require two requests (first to get post and the id of its translations, second to get the desired translation).

**Comment by ririshi** [comment]
I'm using NextJS with SSR, and trying to use pretty permalinks. To identify a unique post, I would like to use its URI or slug. However, using `post(id: $slug, idType: SLUG)` (or a CPT's equivalent) returns `null` for every slug that doesn't match a default language post.

In my use-case, the slugs for different languages will be derived from the translated post's title, so they will (almost certainly) be unique across languages. Having support for querying single posts based on their (translated) slug, would be great.

I could extract the language from the language code from the request URI and use it to set a language filter, if a solution like the one @andyjamesn suggested, was implemented.

Edit: I don't know how I didn't think of this earlier, but a very easy workaround is to use the multiple object version of the query and using the `where` filter, combined with `first`, which allows to get only one post, according to name (slug) and language.

```GraphQL
posts(where: {name: $slug, wpmlLanguage: $languageCode}, first: 1) {
  nodes {
    id
  }
}
```

**Comment by rburgst** [comment]
@Ririshi this sounds like a reasonable approach for now, thanks for sharing
