### ISSUE TITLE
URI of translated page on front should not contain the slug

### ISSUE THREAD

**Issue by macemmek** [rburgst/wp-graphql-wpml#19]
Hello, thank you for your work.

My issue is that when a static page is set as "Page on front" in WordPress and the translation page for it is created, they have the following URI patterns in the CMS:
```
mydomain.com/
mydomain.com/LOCALE/
```
In other words, the front page slug or the post name is removed from the URL.

However, this is not the case when the translated page is retrieved in GraphQL.
We have instead:
```
/
/LOCALE/translated-page-slug/
```

Can this issue be be addressed by this plugin or it should be fixed within a different layer?

Thanks.

**Comment by rburgst** [comment]
@macemmek can you please document the request that you are making (ideally along with the sample response)

**Comment by macemmek** [comment]
Sure!

"Home" is set as page on front in WP, its permalink ends with "/" and its URI is "/".
"Start" is a translation of "Home" in WPML and its permalink ends with "/pl/", while its URI is "/pl/start/"

```
query MyQuery {
  allWpPage(filter: {}) {
    nodes {
      title
      uri
    }
  }
}
```

```
{
  "data": {
    "allWpPage": {
      "nodes": [
        {
          "title": "Przykładowa strona",
          "uri": "/pl/przykladowa-strona/"
        },
        {
          "title": "Start",
          "uri": "/pl/start/"
        },
        {
          "title": "Home",
          "uri": "/"
        },
        {
          "title": "Sample Page",
          "uri": "/sample-page/"
        }
      ]
    }
  },
  "extensions": {}
}
```

**Comment by rburgst** [comment]
when I have a little free time, I will look into that. Right now I am a bit swamped with work. Sorry for the delay.

**Comment by manuliak** [comment]
@macemmek @rburgst 
I solved this problem. Can you check my pull request?

**Comment by rburgst** [comment]
@manuliak thanks a lot, merged
