### ISSUE TITLE
List all posts (in all languages)?

### ISSUE THREAD

**Issue by pmkemper** [rburgst/wp-graphql-wpml#2]
I have installed your plugin, but when I query posts it still only shows the posts in the default language.

How do I query all posts (regardless of language)?

**Comment by rburgst** [comment]
it should usually do that. Which version of WPML are you using?

**Comment by pmkemper** [comment]
A very old one I imagine. Version 3.8.4.

This used to work to get WPGraphQL to work, but it now errors:
```
add_action( 'pre_get_posts', 'mm_show_all_languages_in_graphql' );
function mm_show_all_languages_in_graphql( $query ) {
  if ( function_exists( 'is_graphql_request' ) && true === is_graphql_request() ) {
    $query->query_vars['suppress_filters'] = true;
  }
}
```

**Comment by rburgst** [comment]
the plugin has been tested with 4.3.9. I tried your approach before and that does not work with WPGraphQL anymore as you have found out.
My patch is quite specific to the implementation of WPML. So i am not surprised that it doesnt work with your version.

**Comment by pmkemper** [comment]
I paid for the latest WPML version. Looks to be working now.

**Comment by adriandmitroca** [comment]
Hey guys, how to fetch pages by language?

![image](https://user-images.githubusercontent.com/3842935/95661151-586e7580-0b2d-11eb-9c9f-a7e3f02d43b4.png)

**Comment by PaulBouisset** [comment]
Hi @adriandmitroca did you found a way to query pages by locale ?

**Comment by adriandmitroca** [comment]
I dropped WPML in favor of Polylang (which is probably better in every matter, including plugin for WP GraphQL) but also make some extra requests to WP REST API (which is fine for SSG) to query page by locale as other methods weren't 100% accurate.
