### ISSUE TITLE
Gatsby does not create node for regionalized pages

### ISSUE THREAD

**Issue by wbertolo** [rburgst/wp-graphql-wpml#25]
Hi,

I can query regionalized pages (like pages under /en-gb) on the WordPress graphQL IDE interface. But when Gatsby creates the nodes locally, those pages do not show on the local graphQL queries (using the same id as in the query above) and they show a 404 when I try to access them on the browser. Besides having the plugin installed, do I need to do anything special during the build process? Thanks,

**Comment by wbertolo** [comment]
I figured out what was wrong. Sorry for that.

**Comment by rburgst** [comment]
can I close this then?

**Comment by wbertolo** [comment]
Yes, sorry. I thought I had closed it.
