### ISSUE TITLE
Incompatibility with WPGraphQL WooCommerce (WooGraphQL) and WooCommerce

### ISSUE THREAD

**Issue by opanasenkomaksim** [rburgst/wp-graphql-wpml#26]
Adding a product to the cart is giving an error, while it is working with WPML and WPGraphQL WPML disabled.
I tried to send the query from GraphiQL IDE, Postman and my Next.js app.

The query:
mutation MyMutation {
  addToCart(input: {productId: 32009, clientMutationId: "asdasd", quantity: 1}) {
    cartItem {
      key
    }
  }
}

The error:
{
  "errors": [
    {
      "debugMessage": "Call to a member function get_cart_from_session() on null",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addToCart"
      ],
      "trace": [
        {
          "file": "/wp-content/plugins/wp-graphql-woocommerce/includes/mutation/class-cart-add-item.php",
          "line": 93,
          "call": "WPGraphQL\\WooCommerce\\Data\\Mutation\\Cart_Mutation::check_session_token()"
        },

The website: https://dev.supplybeaver.ca/
Versions:
WPGraphQL WPML - 1.0.7
WPML Multilingual CMS - 4.5.1 
WPGraphQL WooCommerce (WooGraphQL) - 0.10.6
WooCommerce - 5.9.0 
WP GraphQL - 1.6.7

I am creating the same issue for WPGraphQL WooCommerce (WooGraphQL), as I don't know on which side exactly the issue is.
I really hope that it will be possible to use a combination of these plugins on my website soon.
Thank you!

**Comment by rburgst** [comment]
Let me warn you that wp-graphql-wpml is *primarily* designed to run on headless wordpress instances that are *not* accessible to the public internet. I had to do some nasty hacking to get WPML to do what I needed which *will have security implications*!
Therefore, in addition to the inherent risk of running wordpress with plugins on the public internet, this plugin will make matters worse for you (most likely). This plugin is a stop-gap solution until WPML gets their act together and comes with native WP-graphql support.
I use this plugin on a wordpress instance that is in a private net and only serves to allow editors to manage content on a gatsby site. This is where this plugin makes the most amount of sense.

That being said, you stacktrace does not show any code from my plugin, so its not very likely to be involved. However, the plugin does turn on ADMIN mode (which is what I warned you about) which might interfere with woo-commerce session handling.

**Comment by opanasenkomaksim** [comment]
Sure, I understand that this makes sense to use this plugin and other GraphQL plugins only for headless websites. This website installation is a dev environment where we are checking which solution can be used for a headless website, where we will need to use WooCommerce and WPML.
This is nice that we can expect a solution from WPML to use GraphQL with it, but until that it would be nice to use your plugin for that.
You are right, there is no your plugin code in the stack trace and, by the way, enabling ADMIN mode is a string that is making this issue. I noticed this before, but the attempts to add some exclusions there for some reason don't work for me.

$data = file_get_contents('php://input');
if(empty($data) || strpos($data, 'addToCart') === false)
    define('WP_ADMIN', TRUE);

This doesn't look like a serious solution, even if something similar will work

**Comment by opanasenkomaksim** [comment]
The above is not correct as the getting creating session request should be excluded, not adding to the cart, I think or maybe both

**Comment by opanasenkomaksim** [comment]
It seems that I found a working solution.

// define('WP_ADMIN', TRUE);
add_filter('wpml_is_redirected', '__return_false', 10, 3);

**Comment by rburgst** [comment]
@opanasenkomaksim I need to check whether this breaks some of the other functionality. Will come back until the weekend

**Comment by rburgst** [comment]
@opanasenkomaksim your change looks good. This is a much better solution than I had! Thanks a lot!

**Comment by rburgst** [comment]
ups, maybe I have been a bit too early. Somehow the calculation of translations no longer works.

**Comment by rburgst** [comment]
Yes, I do have to do more debugging on how to make it work, with this change, it breaks the calculation of localized urls in non-default languages.

**Comment by opanasenkomaksim** [comment]
@rburgst "Somehow the calculation of translations no longer works." Where it is used and what is for? It seems that this solution is working for our case (we are not using most of the functionality of WPML and WPGraphQL WPML. And this solution is more secure I think.

**Comment by rburgst** [comment]
unfortunately it does not help in case the app no longer works as it should. Right now the calculation of URLs is broken and I need to fix those. I am in the process of doing that, however, we have quite a large gatsby app that uses lots of graphql features. Therefore, fixing issues is a slow process.

**Comment by opanasenkomaksim** [comment]
I see. Okay. Thank you!

**Comment by rburgst** [comment]
I pushed my current state to master, as stated earlier while this fixes the `localizedWpmlUrl` calculation, there still seem to be issues with menus which I still need to debug.

**Comment by opanasenkomaksim** [comment]
Thank you for updates!

**Comment by rburgst** [comment]
Ok, after many hours, it looks as if the change you proposed makes the menuItem url to no longer be correct (for menu items in the non-default language). In my case the menu is `en` and the default language is `de`. 
For english menus I no longer get the `/en/xxxx` prefix that I do get when using 
```php
define('WP_ADMIN', TRUE);
```

**Comment by rburgst** [comment]
the culprit in this case seems to be 
```php
add_filter('pre_wpml_is_translated_post_type', '__return_false');
```
which causes `\WPML_URL_Filters::permalink_filter` to not translate the page permalink correctly.

**Comment by rburgst** [comment]
However, if I remove this line, then the whole content filtering will be active where its no longer possible to iterate over all posts/pages/menuitems regardless of language.

**Comment by rburgst** [comment]
@opanasenkomaksim can you try out the branch `feat/issue-26-remove-admin-hack` and see if this works for you, too? My site looks good and while the fix is similar to using `WP_ADMIN` its a little closer to the truth by simulating `REST_REQUEST`.

**Comment by opanasenkomaksim** [comment]
@rburgst Yes, the issue is fixed. All the queries I am using are working.
Thank you!
