### ISSUE TITLE
Locale field on Product Type (woograpql) ?

### ISSUE THREAD

**Issue by Robak08** [rburgst/wp-graphql-wpml#31]
Hi.

is it possible to extend locale field to Product Type, at the moment this is only visible in Post Types.

**Comment by rburgst** [comment]
Hi, currently i dont have any integration with woo and wont have the time to do that.

**Comment by Robak08** [comment]
Well, I guess I'm gonna try to fiddle a bit with it then, but since I have little to none php knowledge...

Any thanks for response, gonna close this.
