### ISSUE TITLE
Not working with Next.js and language switch

### ISSUE THREAD

**Issue by markdost** [rburgst/wp-graphql-wpml#35]
I'm running into a problem when I query posts for different languages.

Versions used:
WP GraphQL: 1.8.1
WPGraphQL WPML: 1.1.0

My GQL query looks like so:
```
export const getAllPostsForHome = gql`
  query AllPosts($locale: String) {
    posts(
      first: 6
      where: { orderby: { field: DATE, order: DESC }, wpmlLanguage: $locale }
    ) {
      nodes {
        content
        excerpt
        date
        title
        slug
        databaseId
        featuredImage {
          node {
            title
            sourceUrl
          }
        }
      }
    }
  }
`;
``` 

With the variable `locale` I assumed I can then query the posts like so:

```
export async function getStaticProps(context) {
  const { locale } = context;

  const posts = await client.query({
    query: getAllPostsForHome,
    variables: {
      wpmlLanguage: locale,
    },
  });

  return {
    props: {
      posts: posts.data.posts.nodes,
    },
    revalidate: 1,
  };
 }
 ```
  
Instead it queries all posts, the original including translated posts. I might be missing something here?
  
In Next.js I've setup `i18n` in the config file and works as expected. 
`http://localhost:3000/` and `http://localhost:3000/en` works as expected except the posts.

**Comment by rburgst** [comment]
I cannot replicate this problem. On my server I only get the posts in the corresponding language.

**Comment by rburgst** [comment]
Please leave out the whole next.js part and simply use a graphql client such as PostMan or Insomnia. I think your problem might be some bug in your next.js setup.

**Comment by gor3a** [comment]
> I'm running into a problem when I query posts for different languages.
> 
> Versions used: WP GraphQL: 1.8.1 WPGraphQL WPML: 1.1.0
> 
> My GQL query looks like so:
> 
> ```
> export const getAllPostsForHome = gql`
>   query AllPosts($locale: String) {
>     posts(
>       first: 6
>       where: { orderby: { field: DATE, order: DESC }, wpmlLanguage: $locale }
>     ) {
>       nodes {
>         content
>         excerpt
>         date
>         title
>         slug
>         databaseId
>         featuredImage {
>           node {
>             title
>             sourceUrl
>           }
>         }
>       }
>     }
>   }
> `;
> ```
> 
> With the variable `locale` I assumed I can then query the posts like so:
> 
> ```
> export async function getStaticProps(context) {
>   const { locale } = context;
> 
>   const posts = await client.query({
>     query: getAllPostsForHome,
>     variables: {
>       wpmlLanguage: locale,
>     },
>   });
> 
>   return {
>     props: {
>       posts: posts.data.posts.nodes,
>     },
>     revalidate: 1,
>   };
>  }
> ```
> 
> Instead it queries all posts, the original including translated posts. I might be missing something here?
> 
> In Next.js I've setup `i18n` in the config file and works as expected. `http://localhost:3000/` and `http://localhost:3000/en` works as expected except the posts.

Your request should be like that 
```
  const posts = await client.query({
    query: getAllPostsForHome,
    variables: {
      locale: locale,
    },
  });
```

That because your graphql query waiting variable called `$locale`
