### ISSUE TITLE
Does this extension support GraphQL mutation in specific language? 

### ISSUE THREAD

**Issue by MuaathAlhaddad** [rburgst/wp-graphql-wpml#46]
Hi there 

Thanks for creating this amazing extension. 

I am actually working on a project, and I would like to create posts in specific languages using GraphQL mutation. I just could not find that option anywhere in the schema while sending the mutation. 

Does this extension actually support mutation? if yes, pls guide me how,  if not,  Would you consider that in a future update? 

thanks in advance.

**Comment by rburgst** [comment]
No. This plugin was tested and developed only for pulling / querying data from WordPress. 
To be honest I have not tried using it for mutations at all. If it does work then it would be purely by accident.

**Comment by MuaathAlhaddad** [comment]
unfortunately, it does not!

Any intention of developing mutations in the soonest future?

**Comment by rburgst** [comment]
You probably need to wait until there is an official wpml plugin at this point or someone has the time and experience to create a PR.
