### ISSUE TITLE
Classic WPML editor causes non-HTML fields

### ISSUE THREAD

**Issue by sarahannnicholson** [rburgst/wp-graphql-wpml#7]
This plugin has been really awesome so far! :) 

I was using the classic editor and noticed a little bug. 

### Repro steps
1. Go to an english page and make a translation using the classic editor
    For instance, I went into an english page and added an es-mx translation
   
![image](https://user-images.githubusercontent.com/10520771/104765067-261c7780-571d-11eb-896d-86ff55dc2334.png)

2. Feel free to make a new page but using the new editor where you get an entire page
    For instance, this is my french page
![image](https://user-images.githubusercontent.com/10520771/104765327-94f9d080-571d-11eb-8b53-e212952b2d91.png)

3. Go into GraphiQL and run a page query, notice the page translated with the classic editor has a bunch of carriage returns and is not wrapped in an html element:
![image](https://user-images.githubusercontent.com/10520771/104765732-32550480-571e-11eb-8110-f2562c4370f9.png)

### Versions
WP GraphQL: `v1.0.5`
WPGraphQL WPML: `v0.0.1`
WP version : `v5.6`
Gutenberg: `v9.7.2`
WPGraphQL Custom Post Type UI: `v1.1`
WPGraphQL for Advanced Custom Fields: `v0.3.4`
WP Gatsby: `v0.9.1`

**Comment by rburgst** [comment]
Hi, I fear this problem has nothing to do with the plugin itself. I am not modifying the content in any way. My best guess is that this is the way how the WPML plugin stores the data in the database. As typically this is getting rendered back to HTML, newlines should not have any visual effect.

**Comment by sarahannnicholson** [comment]
Hey I just tried to re-pro this and I got valid HTML. Not sure why sometimes I was getting carriage returns and stuff. 

Feel free to close this bug, cause it's probably a WPML issue. 

We were using an HTML parser for our content which wasn't happy with the non-HTML. I'll make my code more robust to take care of non HTML values.
