### ISSUE TITLE
Fetch last posts return 3 times the same posts

### ISSUE THREAD

**Issue by PaulBouisset** [rburgst/wp-graphql-wpml#9]
Hi, 

I am using the last version of WPML and wordpress 5.6.1.

When I query the posts I get all the post but the translated post are also part of the request. For exemple if the last post is translated in two other languages I get 3 times the same post, one for each language. 

The posts and the translations don't have the same post id so I suppose this is why I get them but is this an expected behavior or do I miss something to only query one language at the time?

**Comment by rburgst** [comment]
this is the expected behaviour. When using gatsby (for example which is my use case) you would then filter within the gatsby graphql list.

**Comment by PaulBouisset** [comment]
@rburgst thanks for the quick reply ! 

Then if I understand correctly, if I want the 10 last posts I query the 30 last and filter them on client side based on the locale?

**Comment by rburgst** [comment]
right now this is the way to do it, yes
